version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: middleman
    versions:
    - 4.3.7
