# Site settings
title: Keep a CHANGELOG
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://keepachangelog.com" # the base hostname & protocol for your site

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
exclude: ['LICENSE','CNAME','generate.thor','CONTRIBUTING.md']
  
markdown: kramdown

kramdown:
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false
  line_width:    80
